import io
from datetime import datetime
import markdown2
import html


def generate_html(messages):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    chat_content = ""
    interaction_count = 0

    user_label = "🧑 User"
    assistant_label = "👨🏻‍🏫 AI Tutor"

    for message in messages:
        role = message.get("role", "assistant")
        content = message.get("content", "")

        role_class = "user" if role == "user" else "assistant"
        label = user_label if role_class == "user" else assistant_label

        if role_class == "user":
            interaction_count += 1

        # ✅ Escape HTML for safety
        safe_content = html.escape(content)

        # ✅ Convert markdown → HTML
        formatted_content = markdown2.markdown(safe_content)

        chat_content += f"""
        <div class="message {role_class}">
            <div class="label">{label}</div>
            <div class="text">{formatted_content}</div>
        </div>
        """

    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>EduMentor Chat History</title>
        <meta charset="UTF-8">
        <style>
            body {{
                font-family: Arial, sans-serif;
                background-color: #f5f7fa;
                margin: 0;
                padding: 0;
            }}

            .container {{
                max-width: 800px;
                margin: 20px auto;
                background: white;
                border-radius: 10px;
                box-shadow: 0 2px 8px rgba(0,0,0,0.1);
                overflow: hidden;
            }}

            .header {{
                background-color: #2e7d5b;
                color: white;
                padding: 20px;
                text-align: center;
            }}

            .meta {{
                font-size: 14px;
                opacity: 0.9;
            }}

            .chat {{
                padding: 20px;
                display: flex;
                flex-direction: column;
                gap: 10px;
            }}

            .message {{
                padding: 12px;
                border-radius: 10px;
                max-width: 80%;
            }}

            .user {{
                background-color: #e8f5e9;
                align-self: flex-start;
            }}

            .assistant {{
                background-color: #d0e7ff;
                align-self: flex-end;
            }}

            .label {{
                font-weight: bold;
                margin-bottom: 5px;
            }}

            .text {{
                line-height: 1.5;
            }}

            .footer {{
                background-color: #2e7d5b;
                color: white;
                text-align: center;
                padding: 15px;
                font-size: 14px;
            }}
        </style>
    </head>

    <body>
        <div class="container">
            <div class="header">
                <h2>EduMentor Chat History</h2>
                <div class="meta">Generated on: {timestamp}</div>
                <div class="meta">Total Q&A Interactions: {interaction_count}</div>
            </div>

            <div class="chat">
                {chat_content}
            </div>

            <div class="footer">
                Generated by EduMentor AI Tutor
            </div>
        </div>
    </body>
    </html>
    """

    return html_content